### ISSUE TITLE
Create a Github Actions workflow that creates PRs with new versions of packages

### ISSUE THREAD

**Issue by nathanwn** [nathanwn/dev-env-playbook#1]
# Use Github CLI to get release versions

The following get the latest stable release of neovim.

```
gh release list -R https://github.com/neovim/neovim | grep "Latest" | awk '{print $2}' 
```

# Use GitHub Actions to open PR

See [https://github.com/marketplace/actions/create-pull-request](https://github.com/marketplace/actions/create-pull-request).

# Other notes

* Consider using `group_vars`/`host_vars` to store the versioning values?
* Prototype (?):

```yaml
on:
  schedule:
    - cron: '1 * * * *'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  check:
    name: Check if there is any update and open PR.
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Update versions.yml file
        run: bash "${GITHUB_WORKSPACE}/get_versions.sh" > versions.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        run: gh pr create -B -H branch_to_merge --title 'Update versions.' --body ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
